# Ratings

This notebook is meant to add new features to our listings: the ratings

In [ ]:
import time                                                                                                                                             
from bs4 import BeautifulSoup
import re
import urllib
import requests
import pandas as pd
import numpy as np

def get_result(room_):
    hdr = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11'}
    room=str(room_)
    url = "https://www.airbnb.com/rooms/"
    search= '?guests=1&adults=1'
    url_=url+room+search
    response = requests.get(url_, hdr)
    result_page = BeautifulSoup(response.content,'lxml')
    return result_page

In [52]:
def ratings(room_): 
    result_page = get_result(room_)
    try:
        abc_=result_page.find_all(type="application/json")[2].get_text()
            # AirBNB has 6 main ctaegories in the reviews:

        # Accuracy
        # Communication
        # Cleanliness
        # Location
        # Check-in
        # Value

        #Cleaning
        acc_=(abc_[abc_.rfind('"label":"Accuracy"')-4:abc_.rfind('"label":"Accuracy"')]).replace(':',"").replace(',',"").replace('"',"")
        comm_=(abc_[abc_.rfind('"label":"Communication"')-4:abc_.rfind('"label":"Communication"')]).replace(':',"").replace(',',"").replace('"',"")
        cle_=(abc_[abc_.rfind('"label":"Cleanliness"')-4:abc_.rfind('"label":"Cleanliness"')]).replace(':',"").replace(',',"").replace('"',"")
        loc_=(abc_[abc_.rfind('"label":"Location"')-4:abc_.rfind('"label":"Location"')]).replace(':',"").replace(',',"").replace('"',"")
        che_=(abc_[abc_.rfind('"label":"Check-in"')-4:abc_.rfind('"label":"Check-in"')]).replace(':',"").replace(',',"").replace('"',"")
        val_=(abc_[abc_.rfind('"label":"Value"')-4:abc_.rfind('"label":"Value"')]).replace(':',"").replace(',',"").replace('"',"")
        star_=(abc_[abc_.find('"star_rating"')+14:abc_.find('"star_rating"')+19]).replace(':',
                                                        "").replace(',',"").replace('"',"").replace('t','').replace('i','')

        # Ratings
        rat_=[star_,acc_,comm_,cle_,loc_,che_,val_]
        arr_=np.array(rat_)
        arr_=[arr_]
        # print(arr_)
        # print(np.size(arr_))
        lab_=['Stars','Accuracy','Communication','Cleanliness','Location','Check-In','Value']
        # lab_=np.array(lab_)


        rating_df=pd.DataFrame(arr_,index=[room_],columns=lab_)
        return rating_df
    except:
        print("Didn't work")
        print(room_)
        return pd.DataFrame([[np.NAN, np.NAN, np.NAN, np.NAN, np.NAN, np.NAN, np.NAN]],index = [room_], columns = ['Stars','Accuracy','Communication','Cleanliness','Location','Check-In','Value'])

In [46]:
ratings(3330)

     Stars Accuracy Communication Cleanliness Location Check-In Value
3330     5       10            10          10       10       10    10

In [42]:
filename = 'listings_neibourhood.csv'
data_borough = pd.read_csv(filename)
del data_borough['Unnamed: 0']
data_borough.head()

,id,price,minimum_nights,number_of_reviews,reviews_per_month,availability_365,room_type_Entire home/apt,room_type_Private room,room_type_Shared room,neighbourhood_Harlem,neighbourhood_Morningside Heights,neighbourhood_Upper West Side
0,3647,150,3,0,0.00,365,0,1,0,1,0,0
1,5203,79,2,118,1.03,0,0,1,0,0,0,1
2,5295,135,5,43,0.36,53,1,0,0,0,0,1
3,6021,85,2,100,0.84,365,0,1,0,0,0,1
4,9668,50,3,230,2.02,348,0,1,0,1,0,0

In [43]:
ids = data_borough['id']
len(ids)

5296

In [53]:
rating = ratings(ids.iloc[0])
for i in range(1, len(ids)):
    rating = rating.append(ratings(ids.iloc[i]))
    if i%100 == 0:
        print('step',i)
rating

Didn't work
169002
step 100
Didn't work
304799
Didn't work
334781
Didn't work
450577
Didn't work
535352
step 200
step 300
step 400
step 500
step 600
step 700
step 800
step 900
step 1000
step 1100
Didn't work
6924363
step 1200
step 1300
Didn't work
8195335
step 1400
step 1500
step 1600
Didn't work
9772539
step 1700
Didn't work
10319699
step 1800
step 1900
Didn't work
12115597
step 2000
Didn't work
12326470
Didn't work
12467421
step 2100
step 2200
step 2300
Didn't work
13780778
step 2400
step 2500
step 2600
step 2700
step 2800
step 2900
Didn't work
18448376
step 3000
step 3100
Didn't work
19363071
Didn't work
19378517
step 3200
Didn't work
20263650
Didn't work
20458372
step 3300
Didn't work
21068619
step 3400
step 3500
step 3600
step 3700
step 3800
step 3900
step 4000
step 4100
step 4200
step 4300
step 4400
step 4500
step 4600
step 4700
Didn't work
29900235

ConnectionError: HTTPSConnectionPool(host='www.airbnb.com', port=443): Max retries exceeded with url: /rooms/29924451?guests=1&adults=1&User-Agent=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.11+%28KHTML%2C+like+Gecko%29+Chrome%2F23.0.1271.64+Safari%2F537.11 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x110d7b128>: Failed to establish a new connection: [Errno 60] Operation timed out'))

In [55]:
for i in range(4774, len(ids)):
    rating = rating.append(ratings(ids.iloc[i]))
    if i%100 == 0:
        print('step',i)
rating

Didn't work
29987801
step 4800
step 4900
Didn't work
30359261
Didn't work
30596912
step 5000
step 5100
step 5200

         Stars Accuracy Communication Cleanliness Location Check-In Value
3647      null     }}--          }}--        }}--     }}--     }}--  }}--
5203         5       10            10          10       10       10    10
5295       4.5       10            10           9        9       10     9
6021       4.5        9            10          10        9       10     9
9668       4.5        9             9           7        9        9     9
9704         5       10            10           9       10       10    10
9783       4.5        9             9           7        9        9     9
12318      4.5        9            10          10       10       10     9
12343        5       10            10           9        9       10     9
13552      4.5       10            10          10       10       10    10
14287      4.5       10            10           9       10       10     9
19159      4.5       10            10          10        8        9     9
21456      4.5        9            10           9       10       10     9
21644     null       10            10          10       10       10     8
22918        4        9            10           8        9        9     9
23545        5       10             9          10        9       10     9
25696        5       10            10          10       10       10     9
27006      4.5        9            10           9       10       10     9
27644        5        9            10          10        9       10     9
27759      4.5        9            10           8        9       10     9
29455      4.5        9            10          10        9       10     9
33156        5       10            10          10       10       10    10
39586     ralU     }}--          }}--        }}--     }}--     }}--  }}--
41386     ralU     }}--          }}--        }}--     }}--     }}--  }}--
41513     null       10            10           8        8       10     8
44506      4.5        9             9           9        9        9     9
45542        5       10            10           9        9       10     9
45936      4.5        9            10           9       10       10     9
49715     ralU     }}--          }}--        }}--     }}--     }}--  }}--
54466     null     }}--          }}--        }}--     }}--     }}--  }}--
...        ...      ...           ...         ...      ...      ...   ...
31925803  null       10            10          10       10       10    10
31926655   4.5        9            10           9       10       10     9
31927169  ralU     }}--          }}--        }}--     }}--     }}--  }}--
31927730  ralU     }}--          }}--        }}--     }}--     }}--  }}--
31928077  ralU     }}--          }}--        }}--     }}--     }}--  }}--
31929350  null     }}--          }}--        }}--     }}--     }}--  }}--
31929578  null     }}--          }}--        }}--     }}--     }}--  }}--
31929775  null     }}--          }}--        }}--     }}--     }}--  }}--
31947544  ralU     }}--          }}--        }}--     }}--     }}--  }}--
31949652  ralU     }}--          }}--        }}--     }}--     }}--  }}--
31950040  ralU     }}--          }}--        }}--     }}--     }}--  }}--
31956467  ralU     }}--          }}--        }}--     }}--     }}--  }}--
31957870  ralU     }}--          }}--        }}--     }}--     }}--  }}--
31958321  ralU     }}--          }}--        }}--     }}--     }}--  }}--
31959098  ralU     }}--          }}--        }}--     }}--     }}--  }}--
31961526  ralU     }}--          }}--        }}--     }}--     }}--  }}--
31978375     5       10            10          10       10       10    10
31979408   3.5        8            10           3        9        9     7
31983211  null       10            10          10       10       10    10
31985521  ralU     }}--          }}--        }}--     }}--     }}--  }}--
31987544  null     }}--          }}--        }}--     }}--     }}--  }}--
31987806  null     }}--          }}--        }}--     }}--     }}--  }}--
31988004  null     }}--          }}--        }}--     }}--     }}--  }}--
31988112  null     }}--          }}--        }}--     }}--     }}--  }}--
32015007  null     }}--          }}--        }}--     }}--     }}--  }}--
32036997  null     }}--          }}--        }}--     }}--     }}--  }}--
32041621     5       10            10           8       10       10    10
32042820  null     }}--          }}--        }}--     }}--     }}--  }}--
32045160     4        9            10          10        9        9    10
32053614     5       10            10          10       10        8    10

[5295 rows x 7 columns]

In [58]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5296 entries, 3647 to 29924451
Data columns (total 7 columns):
Stars            5273 non-null object
Accuracy         5273 non-null object
Communication    5273 non-null object
Cleanliness      5273 non-null object
Location         5273 non-null object
Check-In         5273 non-null object
Value            5273 non-null object
dtypes: object(7)
memory usage: 331.0+ KB